export const STRATEGY_CONFIG = {
  symbol:'XAUUSD', contractSize:100, priceDecimals:2, minLot:0.01, lotStep:0.01,
  balance:2000,
  riskPercent:0.5,
  maxRiskPercent:1,
  dailyMaxRiskPercent:3,
  // No daily trade-count / take-profit-count cap. A value of 0 means unlimited.
  maxTradesPerDay:0,
  maxTakeProfitsPerDay:0,
  // Target geometry is derived from Leg-1 length minus spread. These RR bands
  // classify whether a setup is suitable as single-stage or X2/two-stage.
  singleStageMinRR:1,
  singleStageMaxRR:2,
  twoStageMinRR:2,
  twoStageMaxRR:5,
  btbMinRR:2,
  x2Enabled:false,
  x2VolumeMultiplier:2,
  x2CombinedRiskPercent:1,
  maxStopPercent:1.5,
  analysis:{
    minCandles:40,
    opportunityTargetPerDay:10,
    spike:{
      minCandles:3,
      maxCandles:8,
      minBodyQuality:0.45,
      minCloseProgress:0.66,
      minDisplacementATR:0.65,
      minEfficiency:0.42,
      minPressure:0.38,
      resetLookbackBars:3,
      minStartExpansionRatio:1.15,
      maxAgeBars:8,
      activeAgeBars:2,
      maxExtensionATR:5.5,
      maxStopATR:2.00,
      requireDailyTrend:true
    },
    regime:{
      emaLookback:18,minEmaSeparationATR:0.06,minEmaSlopeATR:0.015,minCloseSideRatio:0.55,
      channelLookback:12,rangeLookback:18,minRangeEmaCrosses:4,
      activeM1SpikeBars:2,activeM5SpikeBars:1,activeM15SpikeBars:0
    },
    imbalance:{minGapATR:0.04,atrLength:14},
    pullback:{minRetrace:0.10,maxRetrace:0.70,maxBarsAfterImpulse:4},
    confirmation:{minBodyToRange:0.50,closeInDirection:0.64},
    microMap:{
      minChannelBars:3,maxChannelBars:8,maxPullbackBars:2,maxTriggerDistanceATR:0.70,minFastBreakoutATR:0.25,
      maxStopATR:0.90,minRR:4,maxRR:12,x2Enabled:false
    },
    btb:{
      maxZoneAgeBars:36,returnWindowBars:24,minDepartureBars:2,breakoutLookback:5,
      minDepartureATR:0.70,zonePaddingATR:0.08,maxStopATR:1.75,rejectionCloseATR:0.05,
      maxEntryFromZoneATR:0.55,requireTwoStepM1Rejection:false,
      minM1RejectionBodyToRange:0.50,minM1RejectionCloseInDirection:0.62,
      m1SourceEnabled:false,m5Enabled:true,m15Enabled:true,targetRR:2.0,
      rangeEdgeToleranceATR:0.25,rejectRangeInterior:true
    },
    execution:{minCooldownBars:0,minCooldownAfterLossBars:30,minFavorableRForX2:1.00,minEntryScore:72,maxEntryDriftATR:0.35},
    trendExit:{
      lookbackBars:20,minStrongCandles:2,minBodyToRange:0.55,minCloseLocation:0.65,breakSwingATR:0.05
    },
    context:{
      rangeLookbackBars:25,maxRangeWidthATR:2.8,rangeEdgeToleranceATR:0.25,requireHigherTFSupportWhenH1Neutral:true,
      channelMaxWidthATR:4.5,channelAvgRangeATR:0.95,channelMedianRangeATR:1.05,channelOverlapRatio:0.55,
      rangeMaxWidthATR:2.8,rangeOverlapRatio:0.72,minRangeEmaCrosses:4
    },
    priceAction:{locationMinScore:2,requireLiquidityOrOrderBlock:true,volumeProfileSoftContextOnly:true,requireDirectionalLiquidityEvidence:true,requireSpikeFvgOrOrderBlock:true,requireH1NotOpposing:true,requireM15NotOpposing:false}
  }
};
