export const STRATEGY_CONFIG = {
  symbol: 'XAUUSD',
  contractSize: 100,
  priceDecimals: 2,
  minLot: 0.01,
  lotStep: 0.01,
  balance: 2000,
  riskPercent: 0.5,
  maxRiskPercent: 1,
  dailyMaxRiskPercent: 3,
  targetRR: 2,
  minRR: 1.5,
  maxRR: 4,
  x2Enabled: true,
  x2VolumeMultiplier: 2,
  maxCombinedRiskPercent: 1,
  analysis: {
    minCandles: 30,
    spike: {
      minStrongCandles: 3,
      maxBars: 6,
      bodyToRangeMin: 0.55,
      closeLocationMin: 0.65,
      expansionVsMedian: 1.15,
      maxExtensionATR: 2.00,
      maxStopATR: 2.00,
    },
    imbalance: { minGapATR: 0.08, atrLength: 14 },
    pullback: { minRetrace: 0.00, maxRetrace: 0.65, maxBarsAfterImpulse: 3 },
    confirmation: { minBodyToRange: 0.45, closeInDirection: 0.60 },
    microMap: {
      minChannelBars: 3,
      maxChannelBars: 6,
      maxPullbackBars: 2,
      maxTriggerDistanceATR: 0.80,
      maxStopATR: 1.00,
      targetRR: 4,
      minRR: 3,
      x2Enabled: false,
    },
    btb: {
      maxZoneAgeBars: 18,
      returnWindowBars: 8,
      minDepartureBars: 3,
      breakoutLookback: 5,
      minDepartureATR: 1.0,
      zonePaddingATR: 0.10,
      maxStopATR: 2.0,
      rejectionCloseATR: 0.08,
      maxEntryFromZoneATR: 0.75,
      requireTwoStepM1Rejection: true,
      m5Enabled: true,
      m15Enabled: true,
    },
    execution: {
      minCooldownBars: 3,
      minCooldownAfterLossBars: 5,
    },
  },
};
